client_config_backend: file
client_config:
    client_id: 971374165833-avc2r1ipbr8m74oeabk5unodenl8llng.apps.googleusercontent.com
    client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
    - https://www.googleapis.com/auth/drive